# Generated by Django 5.0.2 on 2024-02-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otp_email", "0005_emaildevice_last_generated_timestamp"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOTPDevice",
            fields=[],
            options={
                "verbose_name": "Email OTP Device",
                "verbose_name_plural": "Email OTP Devices",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("otp_email.emaildevice",),
        ),
        migrations.AddField(
            model_name="user",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("user", "Normal User"), ("admin", "Admin")],
                default="user",
                max_length=50,
            ),
        ),
    ]
