# Generated by Django 5.0.2 on 2024-02-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_emailotpdevice_user_approved_user_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="approved",
            new_name="is_approved",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
